"""Generate a beamer deck of the band diagnostic frames, one slide per step.

One section per model size, each opened by a section title slide, then the
arm's checkpoints in chronological order. Captions are read from `band.jsonl`
rather than typed, so a slide cannot disagree with the metric it shows.

Uses the **pinned-scale** frames from `animate_band.py`, not the per-checkpoint
`diagnostics/` panels: within a section every slide then shares one y-axis and
one CKA color scale, so flipping through the deck shows the metric moving
instead of the axes renormalizing. That is the same reason the animation pins
them, and it matters more here -- slides are compared from memory across a page
turn, where a silently rescaled axis is invisible.

    python scripts/make_band_deck.py --arm 270m --arm 1b --arm 4b \
        --out slides/band_frames.tex
    latexmk -pdf -cd slides/band_frames.tex

Style follows slides/jlens_summary.tex (169, dove, frame-number footline).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

PREAMBLE = r"""% Auto-generated by scripts/make_band_deck.py -- do not hand-edit.
% Build:  latexmk -pdf -cd slides/band_frames.tex
\documentclass[aspectratio=169,10pt]{beamer}

\usetheme{default}
\usecolortheme{dove}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{footline}[frame number]
\setbeamercolor{frametitle}{fg=black}
\setbeamerfont{frametitle}{series=\bfseries}
\setbeamerfont{title}{series=\bfseries}
\setbeamertemplate{itemize items}[circle]

\usepackage{graphicx}
\usepackage{xcolor}
\usepackage[T1]{fontenc}

\graphicspath{{../figs/}{figs/}}

\definecolor{up}{RGB}{20,110,60}
\definecolor{down}{RGB}{170,40,40}
\definecolor{quiet}{RGB}{110,110,110}
\newcommand{\good}[1]{\textcolor{up}{#1}}
\newcommand{\bad}[1]{\textcolor{down}{#1}}
\newcommand{\quietnote}[1]{{\footnotesize\textcolor{quiet}{#1}}}

% Section divider: big centered size label.
\newcommand{\sectionslide}[3]{%
  \begin{frame}[plain]
    \vfill
    \centering
    {\Huge\bfseries #1}\\[0.8em]
    {\large #2}\\[1.6em]
    {\normalsize #3}
    \vfill
  \end{frame}}

\title{Workspace-band diagnostics across medical SFT}
\subtitle{Every probed checkpoint, \texttt{gemma-3-\{270m,1b,4b\}-it}}
\author{}
\date{\today}

\begin{document}

\begin{frame}[plain]
  \titlepage
  \vspace{-1.5em}
  \centering\small
  Full fine-tune on \texttt{mix\_default}, lr $1\mathrm{e}{-5}$, log-spaced
  checkpoints to step 4882. $t=0$ is the untouched base.

  \vspace{0.8em}
  {\footnotesize Panels are \texttt{medlens} Figs.~27--28, rendered by
  \texttt{band.band\_diagnostic\_plot}. Within each section the y-axes and the
  CKA color scale are \textbf{pinned across all steps}, so what moves on the
  page is the metric, not the axis.}
\end{frame}

\begin{frame}{How to read the panel}
  \small
  \begin{columns}[T]
    \begin{column}{0.5\textwidth}
      \textbf{CKA among J-lens vectors} --- linear CKA between layers over a
      subsample of meaningful vocabulary tokens. Block structure exposes the
      sensory / workspace / motor split.

      \vspace{0.5em}
      \textbf{Next-token prediction accuracy} --- fraction of positions where
      any top-10 lens token matches the model's own top-1. Low in the band
      (read-outs carry forward/abstract content), igniting in the motor layers.

      \vspace{0.5em}
      \textbf{Excess kurtosis} --- of the lens-logit distribution over the
      vocabulary. Near zero early, rising once read-outs carry real content.
    \end{column}
    \begin{column}{0.5\textwidth}
      \textbf{Top-1 autocorrelation} --- $P$(top-1 identical at adjacent
      positions) as $\Delta\log p$ against a position-shuffled null. High when
      the J-space carries content that persists across positions.

      \vspace{0.5em}
      \textbf{J-space dimensionality} --- fraction of residual-stream
      dimensions needed for 90\% of the variance across the J-lens vectors.

      \vspace{0.5em}
      \textbf{Green shading} is \texttt{locate\_band}'s \emph{suggested}
      contiguous band --- a suggestion generator, \bad{not human-confirmed}.
      Onset is a threshold on kurtosis and autocorrelation excess, so it can
      flip on a shallow curve; read the curves, not the shading.
    \end{column}
  \end{columns}
\end{frame}
"""


def esc(s: str) -> str:
    return s.replace("_", r"\_")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--arm", action="append", required=True)
    ap.add_argument("--band-root", type=Path, default=Path("eval/band"))
    ap.add_argument("--frames-root", type=Path, default=Path("figs/band"),
                    help="rendered frames; must be reachable via \\graphicspath")
    ap.add_argument("--out", type=Path, default=Path("slides/band_frames.tex"))
    args = ap.parse_args()

    out = [PREAMBLE]
    for arm in args.arm:
        rows = {}
        with (args.band_root / f"{arm}_it" / "band.jsonl").open() as f:
            for line in f:
                r = json.loads(line)
                rows[r["step"]] = r
        steps = sorted(rows)
        first, last = rows[steps[0]], rows[steps[-1]]
        n_layers = first["n_layers"]

        moved = first["band"] != last["band"]
        verdict = (
            f"band moved \\good{{{first['band'][0]}--{first['band'][1]}}} "
            f"$\\rightarrow$ \\good{{{last['band'][0]}--{last['band'][1]}}}"
            if moved else
            f"band \\textbf{{never moved}}: {first['band'][0]}--{first['band'][1]} "
            f"at every step")

        out.append("\n%% " + "-" * 66 + f" {arm}\n")
        out.append(
            "\\sectionslide{\\texttt{%s}}{%d layers $\\cdot$ %d checkpoints + $t{=}0$}{%s}\n"
            % (esc(f"{arm}-it"), n_layers, len(steps) - 1, verdict))

        prev = None
        for step in steps:
            r = rows[step]
            lo, hi = r["band"]
            d0, d1 = r["band_depth"]
            img = args.frames_root / f"{arm}_it" / "frames" / f"step{step:05d}.png"
            label = "$t{=}0$ (untuned base)" if step == 0 else f"step {step}"
            if step == steps[-1] and step != 0:
                label += " (final)"

            if prev is None or r["band"] == prev:
                change = r"\quietnote{unchanged from previous step}" if prev else \
                         r"\quietnote{trajectory origin}"
            else:
                bits = []
                if lo != prev[0]:
                    arrow = "up" if lo > prev[0] else "down"
                    bits.append(f"onset {prev[0]} $\\rightarrow$ \\textbf{{{lo}}} ({arrow})")
                if hi != prev[1]:
                    arrow = "up" if hi > prev[1] else "down"
                    bits.append(f"offset {prev[1]} $\\rightarrow$ \\textbf{{{hi}}} ({arrow})")
                change = r"{\footnotesize " + ", ".join(bits) + "}"

            # The panel strip is ~5:1, so it cannot fill a 16:9 slide however it
            # is placed. Bleed it past the text block to the full paper width
            # (via \makebox, so this is not an overfull hbox) and center the
            # block vertically -- that is all the size available without
            # re-laying-out the figure itself.
            out.append(
                "\\begin{frame}{\\texttt{%s} --- %s}\n"
                "  \\vfill\n"
                "  \\centering\n"
                "  \\makebox[\\textwidth][c]{\\includegraphics[width=\\paperwidth]{%s}}\n\n"
                "  \\vspace{1.0em}\n"
                "  {\\small band: layers \\textbf{%d--%d} (%.0f\\%%--%.0f\\%% of depth)}\n\n"
                "  \\vspace{0.3em}\n"
                "  %s\n"
                "  \\vfill\n"
                "\\end{frame}\n"
                % (esc(f"{arm}-it"), label, img.as_posix().replace("figs/", "", 1),
                   lo, hi, 100 * d0, 100 * d1, change))
            prev = r["band"]

    out.append("\n\\end{document}\n")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(out))

    n_frames = sum(1 for chunk in out if chunk.startswith("\\begin{frame}{\\texttt"))
    print(f"wrote {args.out}: {len(args.arm)} sections, {n_frames} frame slides")


if __name__ == "__main__":
    main()
